'use client'
import { useCallback } from "react"

type RegistryItem = {
  description: string
  docs: string
  importName: string
  jsonPath: string
  name: string
}

const registryItems: RegistryItem[] = [
  {
    description:
      "Virtualized rows, search clauses, grouping, row actions, and persisted table state.",
    docs: "Built for log streams and dense operational datasets.",
    importName: "DataTable",
    jsonPath: "/r/data-table.json",
    name: "data-table",
  },
  {
    description:
      "Interactive timeline view for traces with zooming, markers, search, and a detail side panel.",
    docs: "Includes the worker, CSS module, and trace theme variables needed to render cleanly.",
    importName: "TraceViewer",
    jsonPath: "/r/trace-viewer.json",
    name: "trace-viewer",
  },
  {
    description:
      "A token-aware controlled search input with typed suggestions, possible values, and query-builder interactions.",
    docs: "Works by itself with controlled props, and datool can wire it into searchable views automatically.",
    importName: "SearchBar",
    jsonPath: "/r/search-bar.json",
    name: "search-bar",
  },
  {
    description:
      "React Query hooks and provider helpers that wire queries into the installed data table.",
    docs: "Install this alongside data-table when you want a lightweight query-driven wrapper.",
    importName: "DatoolProvider",
    jsonPath: "/r/react-query-datool.json",
    name: "react-query-datool",
  },
]

function getOrigin() {
  if (typeof window === "undefined") {
    return "https://your-registry.vercel.app"
  }

  return window.location.origin
}

function copyText(value: string) {
  return navigator.clipboard.writeText(value)
}

function App() {
  const origin = getOrigin()
  const registryUrl = `${origin}/registry.json`

  // Tailwind classes replacing original index.css classes
  // For main page-shell: max-w-4xl or max-w-6xl, px-5, py-12, mx-auto, relative, etc.
  // For hero-card: bg-white/80 backdrop-blur-lg rounded-2xl shadow-lg border p-8 mb-8
  // Glows as absolutely positioned divs
  // Headers/text sizing, coloring, etc. converted
  
  return (
    <main className="relative max-w-[1160px] mx-auto px-5 py-12 min-h-screen">
      {/* Glow backgrounds */}
      <div className="absolute top-[-80px] left-[-120px] w-[360px] h-[360px] rounded-full filter blur-[72px] opacity-55 pointer-events-none bg-orange-500/25 z-0" />
      <div className="absolute top-[160px] right-[-120px] w-[360px] h-[360px] rounded-full filter blur-[72px] opacity-55 pointer-events-none bg-pink-700/15 z-0" />

      <section className="relative z-10 bg-white/75 border border-black/10 rounded-[28px] shadow-2xl p-8 mb-12 backdrop-blur-[18px]">
        <p className="uppercase tracking-widest text-xs text-black/60 mb-2 font-semibold">
          shadcn registry
        </p>
        <h1 className="font-serif font-semibold text-4xl md:text-5xl lg:text-6xl leading-tight max-w-[12ch] mt-2 mb-4 tracking-tight">
          Install <span className="whitespace-nowrap">`data-table`</span>, <span className="whitespace-nowrap">`trace-viewer`</span>, <span className="whitespace-nowrap">`search-bar`</span>, and <span className="whitespace-nowrap">`react-query-datool`</span>
          <br className="hidden md:block" />
          straight from this repo.
        </h1>
        <p className="text-base max-w-2xl text-black/80 mt-4 mb-8">
          This deployment serves the registry manifest plus item JSON files generated by <code className="bg-black/5 px-2 py-1 rounded-md">shadcn build</code>. Once it is on Vercel, the commands below are ready to paste into any shadcn-ready app.
        </p>

        <div className="flex flex-wrap gap-3 mt-6">
          <a
            className="inline-flex items-center justify-center min-h-[42px] px-4 py-2 rounded-full border border-black/10 bg-white/80 text-black no-underline hover:bg-white hover:border-black/20 transition"
            href={registryUrl}
          >
            Open <span className="font-mono ml-1">`registry.json`</span>
          </a>
          <button
            className="inline-flex items-center justify-center min-h-[42px] px-4 py-2 rounded-full border border-black/10 bg-white/80 text-black hover:bg-white hover:border-black/20 transition cursor-pointer"
            onClick={() => {
              void copyText(`npx shadcn@latest add ${origin}/r/data-table.json`)
            }}
            type="button"
          >
            Copy <span className="font-mono ml-1">`data-table`</span>
          </button>
          <button
            className="inline-flex items-center justify-center min-h-[42px] px-4 py-2 rounded-full border border-black/10 bg-white/80 text-black hover:bg-white hover:border-black/20 transition cursor-pointer"
            onClick={() => {
              void copyText(
                `npx shadcn@latest add ${origin}/r/trace-viewer.json`
              )
            }}
            type="button"
          >
            Copy <span className="font-mono ml-1">`trace-viewer`</span>
          </button>
          <button
            className="inline-flex items-center justify-center min-h-[42px] px-4 py-2 rounded-full border border-black/10 bg-white/80 text-black hover:bg-white hover:border-black/20 transition cursor-pointer"
            onClick={() => {
              void copyText(`npx shadcn@latest add ${origin}/r/search-bar.json`)
            }}
            type="button"
          >
            Copy <span className="font-mono ml-1">`search-bar`</span>
          </button>
          <button
            className="inline-flex items-center justify-center min-h-[42px] px-4 py-2 rounded-full border border-black/10 bg-white/80 text-black hover:bg-white hover:border-black/20 transition cursor-pointer"
            onClick={() => {
              void copyText(
                `npx shadcn@latest add ${origin}/r/react-query-datool.json`
              )
            }}
            type="button"
          >
            Copy <span className="font-mono ml-1">`react-query-datool`</span>
          </button>
        </div>
      </section>

      <section className="grid grid-cols-1 md:grid-cols-2 gap-5 mt-4 mb-12 z-10">
        {registryItems.map((item) => {
          const url = `${origin}${item.jsonPath}`
          const command = `npx shadcn@latest add ${url}`

          return (
            <article
              className="bg-white/80 border border-black/10 rounded-2xl shadow-lg p-6 flex flex-col gap-3 relative z-10"
              key={item.name}
            >
              <div>
                <p className="uppercase tracking-widest text-xs text-black/65 font-semibold">
                  registry item
                </p>
                <h2 className="font-serif font-semibold text-2xl mt-2">{item.name}</h2>
                <p className="text-black/70 mt-1">{item.description}</p>
              </div>

              <div className="grid gap-2 mt-3">
                <div className="flex flex-col gap-1">
                  <span className="uppercase tracking-widest text-xs text-black/60">
                    Import
                  </span>
                  <code className="inline-block bg-black/5 rounded-full px-3 py-1 font-mono text-sm mt-1">
                    {item.importName}
                  </code>
                </div>
                <p className="text-black/55 text-sm">{item.docs}</p>
              </div>

              <div className="overflow-x-auto rounded-lg bg-black/90 text-white text-sm font-mono p-3 my-3">
                <pre className="whitespace-pre-wrap break-words m-0">{command}</pre>
              </div>

              <div className="flex gap-3 mt-1">
                <a
                  href={url}
                  className="inline-flex items-center px-3 py-2 rounded-full border border-black/10 bg-white/80 text-black transition hover:bg-white hover:border-black/20 text-sm"
                >
                  {item.name}.json
                </a>
                <button
                  className="inline-flex items-center px-3 py-2 rounded-full border border-black/10 bg-white/80 text-black transition hover:bg-white hover:border-black/20 text-sm cursor-pointer"
                  onClick={() => {
                    void copyText(command)
                  }}
                  type="button"
                >
                  Copy command
                </button>
              </div>
            </article>
          )
        })}
      </section>

      <section className="bg-white/90 border border-black/10 rounded-2xl shadow-lg p-6 flex flex-col gap-3 relative z-10 mt-6">
        <div>
          <p className="uppercase tracking-widest text-xs text-black/60 mb-1 font-semibold">manifest</p>
          <h2 className="font-serif font-semibold text-3xl md:text-4xl leading-tight mb-1">
            One root manifest, four installable items.
          </h2>
        </div>
        <div className="overflow-x-auto rounded-lg bg-black/90 text-white text-sm font-mono p-3 my-2">
          <pre className="whitespace-pre-wrap break-words m-0">{registryUrl}</pre>
        </div>
        <p className="text-black/65 text-base mt-1">
          <span className="font-mono">`registry.json`</span> advertises the item catalog. <span className="font-mono">`shadcn build`</span> turns that into the per-item files in <span className="font-mono">`public/r`</span>, which Vercel serves as static JSON.
        </p>
      </section>
    </main>
  )
}

export default App
