type RegistryItem = {
  description: string
  docs: string
  importName: string
  jsonPath: string
  name: string
}

const registryItems: RegistryItem[] = [
  {
    description:
      "Virtualized rows, search clauses, grouping, row actions, and persisted table state.",
    docs: "Built for log streams and dense operational datasets.",
    importName: "DataTable",
    jsonPath: "/r/data-table.json",
    name: "data-table",
  },
  {
    description:
      "Interactive timeline view for traces with zooming, markers, search, and a detail side panel.",
    docs: "Includes the worker, CSS module, and trace theme variables needed to render cleanly.",
    importName: "TraceViewer",
    jsonPath: "/r/trace-viewer.json",
    name: "trace-viewer",
  },
  {
    description:
      "A token-aware controlled search input with typed suggestions, possible values, and query-builder interactions.",
    docs: "Works by itself with controlled props, and datool can wire it into searchable views automatically.",
    importName: "SearchBar",
    jsonPath: "/r/search-bar.json",
    name: "search-bar",
  },
  {
    description:
      "React Query hooks and provider helpers that wire queries into the installed data table.",
    docs: "Install this alongside data-table when you want a lightweight query-driven wrapper.",
    importName: "DatoolProvider",
    jsonPath: "/r/react-query-datool.json",
    name: "react-query-datool",
  },
]

function getOrigin() {
  if (typeof window === "undefined") {
    return "https://your-registry.vercel.app"
  }

  return window.location.origin
}

function copyText(value: string) {
  return navigator.clipboard.writeText(value)
}

function App() {
  const origin = getOrigin()
  const registryUrl = `${origin}/registry.json`

  return (
    <main className="page-shell">
      <div className="page-glow page-glow-left" />
      <div className="page-glow page-glow-right" />

      <section className="hero-card">
        <p className="eyebrow">shadcn registry</p>
        <h1>
          Install `data-table`, `trace-viewer`, `search-bar`, and
          `react-query-datool`
          straight from this repo.
        </h1>
        <p className="hero-copy">
          This deployment serves the registry manifest plus item JSON files
          generated by `shadcn build`. Once it is on Vercel, the commands below
          are ready to paste into any shadcn-ready app.
        </p>

        <div className="hero-actions">
          <a className="hero-link" href={registryUrl}>
            Open `registry.json`
          </a>
          <button
            className="hero-button"
            onClick={() => {
              void copyText(`npx shadcn@latest add ${origin}/r/data-table.json`)
            }}
            type="button"
          >
            Copy `data-table`
          </button>
          <button
            className="hero-button"
            onClick={() => {
              void copyText(
                `npx shadcn@latest add ${origin}/r/trace-viewer.json`
              )
            }}
            type="button"
          >
            Copy `trace-viewer`
          </button>
          <button
            className="hero-button"
            onClick={() => {
              void copyText(`npx shadcn@latest add ${origin}/r/search-bar.json`)
            }}
            type="button"
          >
            Copy `search-bar`
          </button>
          <button
            className="hero-button"
            onClick={() => {
              void copyText(
                `npx shadcn@latest add ${origin}/r/react-query-datool.json`
              )
            }}
            type="button"
          >
            Copy `react-query-datool`
          </button>
        </div>
      </section>

      <section className="install-grid">
        {registryItems.map((item) => {
          const url = `${origin}${item.jsonPath}`
          const command = `npx shadcn@latest add ${url}`

          return (
            <article className="install-card" key={item.name}>
              <div className="install-card-top">
                <p className="install-kicker">registry item</p>
                <h2>{item.name}</h2>
                <p>{item.description}</p>
              </div>

              <div className="install-meta">
                <div>
                  <span className="meta-label">Import</span>
                  <code>{item.importName}</code>
                </div>
                <p className="install-note">{item.docs}</p>
              </div>

              <div className="code-block">
                <pre>{command}</pre>
              </div>

              <div className="card-actions">
                <a href={url}>{item.name}.json</a>
                <button
                  onClick={() => {
                    void copyText(command)
                  }}
                  type="button"
                >
                  Copy command
                </button>
              </div>
            </article>
          )
        })}
      </section>

      <section className="manifest-card">
        <div>
          <p className="eyebrow">manifest</p>
          <h2>One root manifest, four installable items.</h2>
        </div>
        <div className="code-block code-block-wide">
          <pre>{registryUrl}</pre>
        </div>
        <p className="manifest-copy">
          `registry.json` advertises the item catalog. `shadcn build` turns that
          into the per-item files in `public/r`, which Vercel serves as static
          JSON.
        </p>
      </section>
    </main>
  )
}

export default App
